version: '3.8'

services:
  web:
    build: .
    command: ./wait-for-it.sh db:5432 --timeout=60 -- flask run --host=0.0.0.0 --port=5006
    volumes:
      - .:/app
    ports:
      - "5006:5006"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    env_file:
      - .env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
     - "5435:5432"  # Cambiado para que no haya conflictos con pgAdmin
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:

# version: '3.8'

# services:
#   web:
#     build: .
#     command: ./wait-for-it.sh db:5432 --timeout=60 -- flask run --host=0.0.0.0 --port=5006
#     volumes:
#       - .:/app
#     ports:
#       - "5006:5006"
#     environment:
#       - FLASK_ENV=development
#       - DATABASE_URL=${DATABASE_URL}
#       - SECRET_KEY=${SECRET_KEY}
#       - JWT_SECRET_KEY=${JWT_SECRET_KEY}
#     env_file:
#       - .env

#   db:
#     image: postgres:13
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#       - POSTGRES_DB=${POSTGRES_DB}
#     ports:
#      - "5435:5432"
#     env_file:
#       - .env

# volumes:
#   postgres_data:
